services:
  - type: web
    name: tvproxy
    env: python
    region: frankfurt
    buildCommand: docker build -t tvproxy .
    startCommand: docker run -p 8000:8000 tvproxy
    envVars:
      - key: PORT
        value: "8000"
      - key: CACHE_ENABLED
        value: "true"
